### ISSUE TITLE
java.io.IOException: Cannot run program "mvn" 

### ISSUE THREAD

**Issue by mertdeg** [georgewfraser/vscode-javac#22]
I am pretty sure mvn is in my Path (using VSCode with Windows)

Exception details:

java.io.IOException: Cannot run program "mvn" (in directory "c:\enlistments\CentOS\project\common\java\master"): CreateProcess error=2, The system cannot find the file specified
java.lang.RuntimeException: java.io.IOException: Cannot run program "mvn" (in directory "c:\enlistments\CentOS\project\common\java\master"): CreateProcess error=2, The system cannot find the file specified
	at org.javacs.JavaLanguageServer.buildClassPath(JavaLanguageServer.java:562)
	at org.javacs.JavaLanguageServer.readIfConfig(JavaLanguageServer.java:525)
	at org.javacs.JavaLanguageServer.doFindConfig(JavaLanguageServer.java:494)
	at org.javacs.JavaLanguageServer$$Lambda$55/134310351.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at org.javacs.JavaLanguageServer.findConfig(JavaLanguageServer.java:489)
	at org.javacs.JavaLanguageServer.findCompiler(JavaLanguageServer.java:454)
	at org.javacs.JavaLanguageServer.doLint(JavaLanguageServer.java:310)
	at org.javacs.JavaLanguageServer.access$400(JavaLanguageServer.java:31)
	at org.javacs.JavaLanguageServer$1.didOpen(JavaLanguageServer.java:200)
	at io.typefox.lsapi.services.transport.server.LanguageServerEndpoint._doAccept(LanguageServerEndpoint.xtend:198)
	at io.typefox.lsapi.services.transport.server.LanguageServerEndpoint.doAccept(LanguageServerEndpoint.xtend:194)
	at io.typefox.lsapi.services.transport.server.LanguageServerEndpoint.accept(LanguageServerEndpoint.xtend:114)
	at io.typefox.lsapi.services.transport.server.LanguageServerEndpoint.accept(LanguageServerEndpoint.xtend)
	at io.typefox.lsapi.services.transport.AbstractLanguageEndpoint.handleMessage(LanguageEndpoint.xtend:67)
	at io.typefox.lsapi.services.transport.AbstractLanguageEndpoint.lambda$connect$4(LanguageEndpoint.xtend:61)
	at io.typefox.lsapi.services.transport.AbstractLanguageEndpoint$$Lambda$51/1597655940.accept(Unknown Source)
	at io.typefox.lsapi.services.json.StreamMessageReader$1.apply(StreamMessageReader.java:45)
	at io.typefox.lsapi.services.json.StreamMessageReader$1.apply(StreamMessageReader.java:43)
	at io.typefox.lsapi.services.json.StreamMessageReader.handleMessage(StreamMessageReader.xtend:128)
	at io.typefox.lsapi.services.json.StreamMessageReader.listen(StreamMessageReader.xtend:61)
	at io.typefox.lsapi.services.transport.AbstractLanguageEndpoint.connect(LanguageEndpoint.xtend:60)
	at org.javacs.Main.run(Main.java:150)
	at org.javacs.Main.main(Main.java:69)

**Comment by derkoe** [comment]
I think the problem is that the Maven executable in Windows is called "mvn.cmd" (or "mvn.bat" in older versions).
